#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace FadeInOut { class USequenceDirector_C; }

namespace FlashWithImages { class USequenceDirector_C; }

namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace Flash { class USequenceDirector_C; }

